import {useEffect,useRef,useState} from 'react';
import AIModelIcon from './AIModelIcon.jsx';
import './DragonAI.css';

export function AISettings({ai,onClose}){
 const ref=useRef(null);
 useEffect(()=>{ref.current.querySelector('button')?.focus();const dismiss=e=>{if(!ref.current?.contains(e.target)&&!e.target.closest('[data-ai-settings-toggle]'))onClose();};document.addEventListener('pointerdown',dismiss);return()=>document.removeEventListener('pointerdown',dismiss);},[onClose]);
 return <section ref={ref} className="dragon-settings" aria-label="Preferencias de IA" onContextMenu={e=>e.preventDefault()} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();onClose();}}}><header><strong>Preferencias de IA</strong><button type="button" aria-label="Cerrar preferencias" onClick={onClose}>×</button></header><label htmlFor="ai-value">Opacidad <output>{ai.prefs.valor}</output></label><input id="ai-value" type="range" min="0" max="100" step="1" value={ai.prefs.valor} disabled={!ai.ready||ai.saving} onChange={e=>ai.setPrefs(p=>({...p,valor:Number(e.target.value)}))}/><div className="ai-range-labels"><span>0</span><span>100</span></div><div className="ai-models" role="group" aria-label="Modelo de IA">{['chatgpt','gemini'].map(model=><button key={model} type="button" aria-pressed={ai.prefs.modelo===model} disabled={!ai.ready||ai.saving} onClick={()=>ai.setPrefs(p=>({...p,modelo:model}))}><AIModelIcon model={model}/>{model==='chatgpt'?'ChatGPT':'Gemini'}</button>)}</div>{ai.settingsError&&<p role="alert">{ai.settingsError}</p>}{ai.settingsError&&<button type="button" onClick={ai.retrySettings}>Reintentar</button>}</section>;
}

export function AIChat({ai,onSettings,onClose}){
 const [prompt,setPrompt]=useState('');
 const bottom=useRef(null),input=useRef(null),chat=useRef(null),drag=useRef(null),resize=useRef(null);
 const geometry=ai.prefs.x==null?{}:{left:ai.prefs.x,top:ai.prefs.y,width:ai.prefs.ancho,height:ai.prefs.alto,transform:'none'};
 const last=ai.messages.at(-1);
 useEffect(()=>{bottom.current?.scrollIntoView({block:'nearest'});},[last?.id,last?.respuesta,last?.estado]);
 useEffect(()=>{const element=input.current;if(!element)return;element.style.height='auto';const lineHeight=Number.parseFloat(getComputedStyle(element).lineHeight)||21;element.style.height=`${Math.min(element.scrollHeight,lineHeight*3+24)}px`;},[prompt]);
 function saveGeometry(){const element=chat.current;if(!element||!ai.ready)return;const rect=element.getBoundingClientRect();ai.setPrefs(p=>({...p,x:Math.round(rect.left),y:Math.round(rect.top),ancho:Math.round(rect.width),alto:Math.round(rect.height)}));}
 function startDrag(event){if(event.button!==0||event.target.closest('button,textarea,.dragon-resize-handle'))return;const element=chat.current;const rect=element.getBoundingClientRect();drag.current={offsetX:event.clientX-rect.left,offsetY:event.clientY-rect.top};element.classList.add('is-dragging');window.addEventListener('pointermove',moveDrag);window.addEventListener('pointerup',stopDrag,{once:true});window.addEventListener('pointercancel',stopDrag,{once:true});}
 function moveDrag(event){if(!drag.current)return;const element=chat.current;const width=element.offsetWidth;const height=element.offsetHeight;element.style.left=`${Math.max(8,Math.min(window.innerWidth-width-8,event.clientX-drag.current.offsetX))}px`;element.style.top=`${Math.max(8,Math.min(window.innerHeight-height-8,event.clientY-drag.current.offsetY))}px`;element.style.transform='none';}
 function stopDrag(){if(!drag.current)return;window.removeEventListener('pointermove',moveDrag);drag.current=null;chat.current?.classList.remove('is-dragging');saveGeometry();}
 function startResize(event,direction){event.preventDefault();event.stopPropagation();const element=chat.current;const rect=element.getBoundingClientRect();resize.current={direction,startX:event.clientX,startY:event.clientY,width:rect.width,height:rect.height,left:rect.left,top:rect.top};element.classList.add('is-resizing');window.addEventListener('pointermove',moveResize);window.addEventListener('pointerup',stopResize,{once:true});window.addEventListener('pointercancel',stopResize,{once:true});}
 function moveResize(event){if(!resize.current)return;const state=resize.current;const element=chat.current;const dx=event.clientX-state.startX;const dy=event.clientY-state.startY;const resizeLeft=state.direction==='left';const resizeTop=state.direction==='top';const nextWidth=Math.max(300,Math.min(window.innerWidth-16,state.width+(resizeLeft?-dx:dx)));const nextHeight=Math.max(280,Math.min(window.innerHeight-16,state.height+(resizeTop?-dy:dy)));const nextLeft=resizeLeft?state.left+state.width-nextWidth:state.left;const nextTop=resizeTop?state.top+state.height-nextHeight:state.top;element.style.width=`${nextWidth}px`;element.style.height=`${nextHeight}px`;element.style.left=`${Math.max(8,Math.min(window.innerWidth-nextWidth-8,nextLeft))}px`;element.style.top=`${Math.max(8,Math.min(window.innerHeight-nextHeight-8,nextTop))}px`;element.style.transform='none';}
 function stopResize(){if(!resize.current)return;window.removeEventListener('pointermove',moveResize);resize.current=null;chat.current?.classList.remove('is-resizing');saveGeometry();}
 async function submit(e){e.preventDefault();if(await ai.send(prompt))setPrompt('');}
 return <section ref={chat} className="dragon-chat" aria-label="Chat del campus" style={{...geometry,opacity:ai.prefs.valor/100}} onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={stopDrag} onPointerCancel={stopDrag}><header><div><span>DRAGÓN · IA</span><h2><AIModelIcon model={ai.prefs.modelo}/>{ai.prefs.modelo==='chatgpt'?'ChatGPT':'Gemini'}</h2></div><div><button type="button" data-ai-settings-toggle aria-label="Abrir ajustes" title="Ajustes" onClick={onSettings}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M19.43 12.98c.04-.32.07-.65-.07-.98s-.02-.66-.07-.98l2.11-1.65-2-3.46-2.49 1a7.3 7.3 0 0 0-1.69-.98L15 3.5h-4l-.36 2.43c-.61.25-1.18.58-1.69.98l-2.49-1-2 3.46 2.11 1.65c-.04.32-.07.66-.07.98s.02.66.07.98l-2.11 1.65 2 3.46 2.49 1 1.69.98L11 20.5h4l.36-2.43c.61.25-1.18.58-1.69.98l2.49 1 1.69-.98 2.49 1 2-3.46-2.11-1.65zM13 15.5A3.5 3.5 0 1 1 13 8a3.5 3.5 0 0 1 0 7.5z"/></svg></button><button type="button" onClick={onClose} aria-label="Cerrar chat">×</button></div></header><div className="dragon-messages" tabIndex={0} aria-label="Historial de mensajes">{ai.loading&&<p role="status">Cargando mensajes…</p>}{!ai.loading&&!ai.messages.length&&<div className="ai-empty"><h3>¿Qué quieres preguntar?</h3><p>Escribe un mensaje. Tu proyecto Python recogerá la petición y devolverá aquí la respuesta.</p></div>}{ai.messages.map(message=><article key={message.id} className="ai-exchange"><div className="ai-prompt"><small>Tú · {message.modelo==='chatgpt'?'ChatGPT':'Gemini'}</small><p>{message.prompt}</p></div><div className="ai-answer"><small><AIModelIcon model={message.modelo}/>{message.modelo==='chatgpt'?'ChatGPT':'Gemini'}</small><p>{message.estado==='completado'?message.respuesta:message.estado==='error'?(message.error||'No se pudo obtener una respuesta.'):message.estado==='procesando'?'Python está procesando tu mensaje…':'Esperando a Python…'}</p></div></article>)}<div ref={bottom}/></div>{ai.chatError&&<p className="ai-error" role="alert">{ai.chatError}</p>}<form onSubmit={submit}><label className="ai-input-label" htmlFor="ai-prompt">Tu mensaje</label><textarea ref={input} id="ai-prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={20000} rows={1} required placeholder="Escribe tu prompt…" disabled={ai.sending}/><footer><small>Últimos 50 mensajes · respuestas sincronizadas</small><button type="submit" disabled={!ai.ready||ai.dirty||ai.saving||ai.sending||!prompt.trim()}>{ai.sending?'Enviando…':'Enviar'}</button></footer></form> <span className="dragon-resize-handle dragon-resize-right" onPointerDown={e=>startResize(e,'right')}/><span className="dragon-resize-handle dragon-resize-left" onPointerDown={e=>startResize(e,'left')}/><span className="dragon-resize-handle dragon-resize-bottom" onPointerDown={e=>startResize(e,'bottom')}/><span className="dragon-resize-handle dragon-resize-top" onPointerDown={e=>startResize(e,'top')}/></section>;
}
