import {useCallback,useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {useEmergencyChat} from '../lib/useEmergencyChat.js';
import './EmergencyIndicator.css';

function EmergencyIcon(){return <svg viewBox="0 -960 960 960" aria-hidden="true"><path d="M200-160v-80h64l79-263q8-26 29.5-41.5T420-560h120q26 0 47.5 15.5T617-503l79 263h64v80H200Zm148-80h264l-72-240H420l-72 240Zm92-400v-200h80v200h-80Zm238 99-57-57 142-141 56 56-141 142Zm42 181v-80h200v80H720ZM282-541 141-683l56-56 142 141-57 57ZM40-360v-80h200v80H40Zm440 120Z"/></svg>;}

function EmergencySettings({chat,onClose}){
 return <section className="emergency-settings" aria-label="Ajustes de Emergencias" onContextMenu={event=>event.preventDefault()}><header><strong>Emergencias</strong><button type="button" aria-label="Cerrar ajustes" onClick={onClose}>×</button></header><label htmlFor="emergency-opacity">Opacidad <output>{chat.prefs.valor}</output></label><input id="emergency-opacity" type="range" min="0" max="100" value={chat.prefs.valor} onChange={event=>chat.setPrefs(p=>({...p,valor:Number(event.target.value)}))}/><div className="emergency-range-labels"><span>0</span><span>100</span></div>{chat.error&&<p role="alert">{chat.error}</p>}</section>;
}

function CloseIcon(){return <svg viewBox="0 -960 960 960" aria-hidden="true"><path d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h280v80H200v560h280v80H200Zm440-160-55-58 102-102H360v-80h327L585-622l55-58 200 200-200 200Z"/></svg>;}
function DeleteIcon(){return <svg viewBox="0 -960 960 960" aria-hidden="true"><path d="m376-300 104-104 104 104 56-56-104-104 104-104-56-56-104 104-104-104-56 56 104 104-104 104 56 56Zm-96 180q-33 0-56.5-23.5T200-200v-520h-40v-80h200v-40h240v40h200v80h-40v520q0 33-23.5 56.5T680-120H280Zm400-600H280v520h400v-520Z"/></svg>;}
function AlertIcon(){return <svg viewBox="0 -960 960 960" aria-hidden="true"><path d="M449.5-85Q435-91 423-102L102-423q-11-12-17-26.5T79-480q0-16 6-31t17-26l321-321q12-12 26.5-17.5T480-881q16 0 31 5.5t26 17.5l321 321q11 11 17 26t6 31q0 16-6 30.5T858-423L537-102q-11 11-26 17t-31 6q-16 0-30.5-6ZM480-159l321-321-321-321-321 321 321 321Zm-40-281h80v-240h-80v240Zm40 120q17 0 28.5-11.5T520-360q0-17-11.5-28.5T480-400q-17 0-28.5 11.5T440-360q0 17 11.5 28.5T480-320Z"/></svg>;}
function EmergencyChat({chat,onClose}){
 const [text,setText]=useState(''),[view,setView]=useState('list');const panel=useRef(null),drag=useRef(null),resize=useRef(null),input=useRef(null);
 const geometry=chat.prefs.x==null?{}:{left:chat.prefs.x,top:chat.prefs.y,width:chat.prefs.ancho,height:chat.prefs.alto,transform:'none'};
 useEffect(()=>{const element=input.current;if(!element)return;element.style.height='auto';const lineHeight=Number.parseFloat(getComputedStyle(element).lineHeight)||21;element.style.height=`${Math.min(element.scrollHeight,lineHeight*3+24)}px`;},[text]);
 function saveGeometry(){const rect=panel.current?.getBoundingClientRect();if(rect)chat.setPrefs(p=>({...p,x:Math.round(rect.left),y:Math.round(rect.top),ancho:Math.round(rect.width),alto:Math.round(rect.height)}));}
 function startDrag(event){if(event.button!==0||!event.target.closest('header')||event.target.closest('button,.emergency-resize-handle'))return;const rect=panel.current.getBoundingClientRect();drag.current={x:event.clientX-rect.left,y:event.clientY-rect.top};panel.current.classList.add('is-dragging');const move=e=>{if(!drag.current)return;panel.current.style.left=`${Math.max(8,Math.min(innerWidth-panel.current.offsetWidth-8,e.clientX-drag.current.x))}px`;panel.current.style.top=`${Math.max(8,Math.min(innerHeight-panel.current.offsetHeight-8,e.clientY-drag.current.y))}px`;panel.current.style.transform='none';};const stop=()=>{window.removeEventListener('pointermove',move);drag.current=null;panel.current?.classList.remove('is-dragging');saveGeometry();};window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop,{once:true});}
 function startResize(event,direction){event.preventDefault();event.stopPropagation();const rect=panel.current.getBoundingClientRect();resize.current={direction,x:event.clientX,y:event.clientY,width:rect.width,height:rect.height,left:rect.left,top:rect.top};const move=e=>{const s=resize.current;if(!s)return;const left=s.direction==='left',top=s.direction==='top';const width=Math.max(300,Math.min(innerWidth-16,s.width+(left?event.clientX-e.clientX:e.clientX-event.clientX)));const height=Math.max(280,Math.min(innerHeight-16,s.height+(top?event.clientY-e.clientY:e.clientY-event.clientY)));panel.current.style.width=`${width}px`;panel.current.style.height=`${height}px`;panel.current.style.left=`${Math.max(8,Math.min(innerWidth-width-8,left?s.left+s.width-width:s.left))}px`;panel.current.style.top=`${Math.max(8,Math.min(innerHeight-height-8,top?s.top+s.height-height:s.top))}px`;panel.current.style.transform='none';};const stop=()=>{window.removeEventListener('pointermove',move);resize.current=null;panel.current?.classList.remove('is-resizing');saveGeometry();};panel.current.classList.add('is-resizing');window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop,{once:true});}
 async function submit(event){event.preventDefault();if(await chat.send(text))setText('');}
 async function closeSelected(){if(window.confirm(`¿Cerrar el chat de ${chat.selectedChat?.remitente}?`))await chat.closeChat(chat.selectedChat);}
 async function deleteSelected(){if(!chat.selectedChat?.activo&&window.confirm(`¿Borrar todos los mensajes y el chat de ${chat.selectedChat?.remitente}?`)){await chat.deleteChat(chat.selectedChat);setView('list');}}
 function openChat(item){if(!item.id)return;chat.setSelectedChat(item);setView('chat');}
 const chatCard=item=><button type="button" className={`emergency-chat-open${chat.alertIds.has(item.id)?' has-incoming':''}`} onClick={()=>{chat.acknowledgeChat(item);openChat(item);}}><span>{item.remitente}</span><small>{item.activo?'Chat activo':'Chat cerrado'}</small>{chat.alertIds.has(item.id)&&<AlertIcon/>}</button>;
 function handleMessageKeyDown(event){if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();submit(event);}}
 return <section ref={panel} className="emergency-chat" style={{...geometry,opacity:chat.prefs.valor/100}} onPointerDown={startDrag} aria-label="Chats de emergencia"><header><div className={`emergency-header-content${view==='chat'?' is-chat':''}`}>{view==='chat'&&<div className="emergency-back-row"><button type="button" aria-label="Volver a chats" onClick={()=>{chat.setSelectedChat(null);setView('list');}}>←</button><span>EMERGENCIAS</span></div>}{view==='list'&&<span>EMERGENCIAS</span>}<h2><EmergencyIcon/>{view==='chat'?chat.selectedChat?.remitente:'Chats activos'}</h2></div><button type="button" aria-label="Cerrar emergencias" onClick={onClose}>×</button></header>{view==='list'?<main className="emergency-list">{chat.loading?<p>Cargando chats...</p>:<><h3>Fijados</h3><div className="emergency-pinned">{chat.fixedChats.map(item=><div className="emergency-chat-card" key={item.id}>{chatCard(item)}</div>)}</div><h3>Chats de emergencia</h3>{!chat.activeChats.length?<p>No hay chats activos.</p>:<div className="emergency-active-list">{chat.activeChats.map(item=><div className="emergency-chat-card" key={item.id}>{chatCard(item)}</div>)}</div>}</>}</main>:<><main className="emergency-messages">{chat.messages.map(item=><article key={item.id} className={item.direccion==='salida'?'is-outgoing':''}><small>{item.direccion==='salida'?'Tú':item.remitente}</small><p>{item.mensaje}</p></article>)}</main><div className="emergency-chat-actions emergency-chat-actions-footer"><button type="button" onClick={closeSelected} disabled={!chat.selectedChat?.activo}><CloseIcon/>Cerrar chat</button><button type="button" onClick={deleteSelected} disabled={chat.selectedChat?.activo}><DeleteIcon/>Borrar chat</button></div><form onSubmit={submit}><textarea ref={input} value={text} onChange={event=>setText(event.target.value)} onKeyDown={handleMessageKeyDown} placeholder="Escribe un mensaje..." rows="1"/><button type="submit" disabled={chat.sending||!text.trim()}>Enviar</button></form></>}<div className="emergency-resize-handle emergency-resize-right" onPointerDown={event=>startResize(event,'right')}/><div className="emergency-resize-handle emergency-resize-left" onPointerDown={event=>startResize(event,'left')}/><div className="emergency-resize-handle emergency-resize-bottom" onPointerDown={event=>startResize(event,'bottom')}/><div className="emergency-resize-handle emergency-resize-top" onPointerDown={event=>startResize(event,'top')}/></section>;
}

export default function EmergencyIndicator({userId}){
 const [active,setActive]=useState(false),[open,setOpen]=useState(false),[settings,setSettings]=useState(false);const clearTimer=useRef(null);const chat=useEmergencyChat(userId,open);const close=useCallback(()=>{setOpen(false);setSettings(false);},[]);
 useEffect(()=>{if(chat.hasEmergencyAlert)setActive(true);},[chat.hasEmergencyAlert]);
 function clearAlertByHold(){clearTimer.current=window.setTimeout(()=>{chat.clearAlerts();setActive(false);},700);}
 function cancelClearAlert(){if(clearTimer.current){window.clearTimeout(clearTimer.current);clearTimer.current=null;}}
 useEffect(()=>{const handler=event=>{if(event.defaultPrevented||event.repeat||!event.ctrlKey||!event.altKey||event.shiftKey||event.metaKey||event.code!=='KeyE')return;event.preventDefault();setSettings(false);setActive(value=>{if(value){setOpen(false);return false;}return true;});};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 return <><button type="button" className={`emergency-indicator${active?' is-active':''}${chat.hasEmergencyAlert?' has-alert':''}`} aria-hidden={!active} tabIndex={active?0:-1} aria-label="Abrir emergencias" onPointerDown={clearAlertByHold} onPointerUp={cancelClearAlert} onPointerLeave={cancelClearAlert} onClick={()=>{setSettings(false);setOpen(value=>!value);}} onContextMenu={event=>{event.preventDefault();setSettings(value=>!value);}}><EmergencyIcon/></button>{settings&&!open&&createPortal(<EmergencySettings chat={chat} onClose={()=>setSettings(false)}/>,document.body)}{open&&createPortal(<EmergencyChat chat={chat} onClose={close}/>,document.body)}{settings&&open&&createPortal(<EmergencySettings chat={chat} onClose={()=>setSettings(false)}/>,document.body)}</>;
}
